FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime

ENV LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/opt/conda/lib/"

RUN mkdir /app
COPY ./requirements.txt /app
WORKDIR /app
RUN pip install -r requirements.txt

COPY ./main.py /app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]